# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    unnecessary_this: false
    prefer_single_quotes: false
    slash_for_doc_comments: false
    omit_local_variable_types: false
    

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    unrelated_type_equality_checks: error
#   exclude:
#     - path/to/excluded/files/**
