name: y_crdt
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  logger: 1.0.0-nullsafety.0
  fixnum: 1.0.0-nullsafety.0
  uuid:
    git: 
      url: https://github.com/Daegalus/dart-uuid
      ref: acca9f98eb00094d028a61f2f5a364635a8e0a0f

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.12

dependency_overrides:
  crypto:
    git:
      url: https://github.com/dart-lang/crypto.git
      ref: "3.0"
  convert: ^3.0.0-nullsafety
